language: cpp

matrix:
  include:
    - os: linux
      cache:
        directories:
          - /var/cache/apt/archives/*.deb
      compiler: gcc
      sudo: require
      dist: trusty
      services:
        - docker
    - os: osx

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build-${TRAVIS_OS_NAME}.sh

after_success:
  - ls -lh travis-out/*
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh travis-out/*

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
